apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - app.asgard.local
        - api.asgard.local
        - api-py.asgard.local
        - api-dotnet.asgard.local
      secretName: app-tls
  rules:
    # Frontend web (nginx faz proxy para api-go internamente)
    - host: app.asgard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: meu-app-web
                port:
                  number: 80
    # API Go (acesso direto â€” protegido por CORS/CSRF)
    - host: api.asgard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-go
                port:
                  number: 8080
    # API Python
    - host: api-py.asgard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-python
                port:
                  number: 8081
    # API .NET
    - host: api-dotnet.asgard.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-dotnet
                port:
                  number: 8082
