apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-tst

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: meu-app-web
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: api-go
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: api-python
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: api-dotnet
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

images:
  - name: meu-app-web
    newName: harbor.asgard.local/tst/meu-app-web
    newTag: develop
  - name: api-go
    newName: harbor.asgard.local/tst/api-go
    newTag: develop
  - name: api-python
    newName: harbor.asgard.local/tst/api-python
    newTag: develop
  - name: api-dotnet
    newName: harbor.asgard.local/tst/api-dotnet
    newTag: develop

commonLabels:
  environment: tst

configMapGenerator:
  - name: app-config
    literals:
      - ENVIRONMENT=staging
      - LOG_LEVEL=debug
      - CORS_ORIGINS=https://app.tst.asgard.local
